module: "DataWriter"
epochs: 1
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/race_train_l2lsh.pickle"
  dataset: "race_pp"
  race_pp:
    epoch_samples: 500
    parallel_batch: 500
    method: "m1"
    m1:
      minover:
        max_iters: 100
        speed: 1
  
  sampler: "simple"
  simple:
    batch_size: 500
write_data_file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/race_train_l2lsh_sampled_TEMP.txt"
