module: "RaceSketch"
data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/train.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 784
  sampler: "simple"
  simple:
    batch_size: 500
save_sketch: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/race_train_l2lsh_m2.pickle"
np_seed: 101
race:
  range: 5000 # (2*max_norm / bandwidth + 1)*power
  repetitions: 5000
  power: 1
  num_classes: 10
  rehash: False
  max_coord: 1
  min_coord: 0
  lsh_function:
    name: "l2lsh"
    l2lsh:
      bandwidth: 0.01
      dimension: 784
      max_norm: 18
