module: "RaceSketch"
data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/letter/train.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 16
    base_idx: 1
    class_base_idx: 1
  sampler: "simple"
  simple:
    batch_size: 20000
save_sketch: "/home/apd10/experiments/projects/summary_based_learning/DATA/letter/race_sketch.pickle"
np_seed: 101
race:
  range: 4294967295 # (2*max_norm / bandwidth + 1)*power
  power: 5
  repetitions: 50
  num_classes: 26
  rehash: False
  max_coord: 1
  min_coord: -1
  lsh_function:
    name: "l2lsh"
    l2lsh:
      bandwidth: 0.1
      dimension: 16
      max_norm: 3.2
