module: "Loop"
device_id: 0
epochs: 100
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/letter/race_train_l2lsh_sampled.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/letter/test.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 16
    base_idx: 1
    class_base_idx: 1
  sampler: "simple"
  simple:
    batch_size: 64
validation_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/letter/test.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 16
    base_idx: 1
    class_base_idx: 1
  sampler: "simple"
  simple:
    batch_size: 64
progress_train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/letter/race_small_train.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/letter/test.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 16
    base_idx: 1
    class_base_idx: 1
  sampler: "simple"
  simple:
    batch_size: 64
model:
  name: "MLP"
  MLP:
    input_dim: 16
    num_layers: 4
    hidden_size: 500
    num_class: 26
optimizer:
  name: "adam"
  adam:
    lr: 0.01
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 100000000
      eval_epoch: 1
