module: "Loop"
device_id: 6
epochs: 10
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/skin_nonskin.dt/race_train.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/skin_nonskin.dt/test.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
    normalizer_const: 255
  sampler: "simple"
  simple:
    batch_size: 64
validation_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/skin_nonskin.dt/test.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
    normalizer_const: 255
  sampler: "simple"
  simple:
    batch_size: 64
progress_train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/skin_nonskin.dt/race_small_train.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/skin_nonskin.dt/test.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
    normalizer_const: 255
  sampler: "simple"
  simple:
    batch_size: 64
model:
  name: "MLP"
  MLP:
    input_dim: 3
    num_layers: 1
    hidden_size: 2
    num_class: 2
optimizer:
  name: "adam"
  adam:
    lr: 0.01
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 100000000
      eval_epoch: 1
