module: "Loop"
device_id: 0
epochs: 21
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/DATASET/train.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
    centering_info: "/home/apd10/experiments/projects/summary_based_learning/DATA/DATASET/centering_info.npz"
  sampler: "simple"
  simple:
    batch_size: 64
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/DATASET/test.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
    centering_info: "/home/apd10/experiments/projects/summary_based_learning/DATA/DATASET/centering_info.npz"
  sampler: "simple"
  simple:
    batch_size: 1000
model:
  name: "MLP"
  MLP:
    input_dim: DIM
    num_layers: 3
    hidden_size: DIM
    num_class: 2
optimizer:
  name: "adam"
  adam:
    lr: 0.001
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 500000000
      eval_epoch: 5
      csv_dump: "/home/apd10/experiments/projects/summary_based_learning/DATA/DATASET/record/log.train.csv"
