module: "Loop"
device_id: 6
epochs: 10
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/concept_shift/train_race_counts.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/concept_shift/test_race_counts.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
validation_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/concept_shift/test_race_counts.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/concept_shift/test_race_counts.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/concept_shift/test_race_counts.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
model:
  name: "MLP"
  MLP:
    input_dim: 100
    num_layers: 3
    hidden_size: 100
    num_class: 10
optimizer:
  name: "adam"
  adam:
    lr: 0.001
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 100000
      eval_epoch: 1
