module: "Loop"
device_id: 6
epochs: 10
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/FashionMnist/race_train.pickle"
  dataset: "race"
  race:
    epoch_samples: 60000
  sampler: "simple"
  simple:
    batch_size: 64
test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/FashionMnist/test.txt"
  dataset: "csv"
  csv:
    sep: ","
    header: "infer"
    label_header: "label"
    normalizer_const: 255
  sampler: "simple"
  simple:
    batch_size: 1000
validation_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/FashionMnist/test_small.txt"
  dataset: "csv"
  csv:
    sep: ","
    header: "infer"
    label_header: "label"
    normalizer_const: 255
  sampler: "simple"
  simple:
    batch_size: 1000
progress_train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/FashionMnist/train_small.txt"
  dataset: "csv"
  csv:
    sep: ","
    header: "infer"
    label_header: "label"
    normalizer_const: 255
  sampler: "simple"
  simple:
    batch_size: 1000
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/FashionMnist/test.txt"
  dataset: "csv"
  csv:
    sep: ","
    header: "infer"
    label_header: "label"
    normalizer_const: 255
  sampler: "simple"
  simple:
    batch_size: 1000
model:
  name: "MLP"
  MLP:
    input_dim: 784
    num_layers: 3
    hidden_size: 100
    num_class: 10
optimizer:
  name: "adam"
  adam:
    lr: 0.001
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 100000000
      eval_epoch: 1
