module: "DataWriter"
epochs: 1
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist8m/race_sketch_gen.pickle"
  dataset: "race_gen_pp"
  race_gen_pp:
    epoch_samples: 10
    parallel_batch: 10
    method: "m1"
    m1:
      minover:
        max_iters: 10
        speed: 10
  sampler: "simple"
  simple:
    batch_size: 10
write_data_file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist8m/race_train_l2lsh_sampled_p5.txt"
