module: "RaceSketch"
data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/FashionMnist/train.txt"
  dataset: "csv"
  csv:
    sep: ","
    header: "infer"
    label_header: "label"
    normalizer_const: 255
  sampler: "simple"
  simple:
    batch_size: 500
save_sketch: "/home/apd10/experiments/projects/summary_based_learning/DATA/FashionMnist/race_train.pickle"
np_seed: 101
race:
  range: 1050000
  repetitions: 10
  power: 20
  num_classes: 10
  rehash: False
  lsh_function:
    name: "srp"
    srp:
      dimension: 784
