module: "DataWriter"
epochs: 1
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/simulated/race_train_l2lsh.pickle"
  dataset: "race"
  race:
    epoch_samples: 4000
  sampler: "simple"
  simple:
    batch_size: 100
write_data_file: "/home/apd10/experiments/projects/summary_based_learning/DATA/simulated/race_train_l2lsh_sampled.txt"
