module: "DataWriter"
epochs: 1
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/pca_mnist/race_train_l2lsh.pickle"
  dataset: "race_pp"
  race_pp:
    epoch_samples: 50
    parallel_batch: 50
    method: "m1"
    m1:
      minover:
        max_iters: 1000
        speed: 1
  sampler: "simple"
  simple:
    batch_size: 50
write_data_file: "/home/apd10/experiments/projects/summary_based_learning/DATA/pca_mnist/race_train_l2lsh_sampled.txt"
