module: "RaceGenSketch"
data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/centered_train.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 784
  sampler: "simple"
  simple:
    batch_size: 10000
save_sketch: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/parameter_tuning/sketch.POWER.REP.BWIDTH.HEAP.pickle"
np_seed: 101
race:
  power: POWER
  repetitions: REP
  num_classes: 10
  max_coord: 1
  min_coord: -1
  random_seed: 101
  ace_type: "cs"
  ace_params:
    rep : 5
    range : 50000
    num_keys : POWER # equal to the power
    device_id : -1 # to do on cpu. test device as well later
    sketch_type : "CMS" # we only store counts
    recovery : "min" # min recovery
    topK : HEAP # top 1000 buckets should be good
  lsh_function:
    name: "l2lsh_torch"
    l2lsh_torch:
      bandwidth: BWIDTH
      dimension: 784
      max_norm: 17
      device_id: -1
