/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.10.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.10.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.10.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.25.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.25.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.25.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.50.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.50.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.5.50.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.10.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.10.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.10.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.25.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.25.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.25.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.50.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.50.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.10.50.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.10.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.10.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.10.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.25.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.25.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.25.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.50.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.50.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.50.50.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.10.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.10.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.10.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.25.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.25.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.25.0.4.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.50.0.1.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.50.0.2.5000.yml  &
/home/apd10/experiments/projects/summary_based_learning/run.py --config /home/apd10/experiments/projects/summary_based_learning/train_configs/mnist/parameter_tuning/sketch.100.50.0.4.5000.yml  &
