module: "Loop"
device_id: 6
epochs: 50
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/simple2d/train_1_race_counts.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 64
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/simple2d/test_1_2_race_counts.txt"
  dataset: "csv"
  csv:
    sep: " "
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 1000
model:
  name: "MLP"
  MLP:
    input_dim: 20
    num_layers: 3
    hidden_size: 10
    num_class: 2
optimizer:
  name: "adam"
  adam:
    lr: 0.001
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 100000
      eval_epoch: 1
