module: "Loop"
device_id: 6
epochs: 10
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/race_train_l2lsh.pickle"
  dataset: "race_pp"
  race_pp:
    epoch_samples: 60000
    parallel_batch: 1000
    method: "m1"
    m1:
      minover:
        max_iters: 100
        speed: 1
  sampler: "simple"
  simple:
    batch_size: 64
test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/test.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 784
  sampler: "simple"
  simple:
    batch_size: 1000
validation_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/test_small.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 784
  sampler: "simple"
  simple:
    batch_size: 1000
progress_train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/train_small.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 784
  sampler: "simple"
  simple:
    batch_size: 1000
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/mnist/data/test.txt"
  dataset: "gensvm"
  gensvm:
    dimension: 784
  sampler: "simple"
  simple:
    batch_size: 1000
model:
  name: "MLP"
  MLP:
    input_dim: 784
    num_layers: 3
    hidden_size: 100
    num_class: 10
optimizer:
  name: "adam"
  adam:
    lr: 0.001
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 10
      eval_epoch: 1
