module: "DataWriter"
epochs: 1
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/race_sketch_gen.pickle"
  dataset: "race_gen_pp"
  race_gen_pp:
    epoch_samples: 5000000
    parallel_batch: 10000
    method: "m1"
    m1:
      minover:
        max_iters: 20
        speed: 1
  sampler: "simple"
  simple:
    batch_size: 50
write_data_file: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/race_train_l2lsh_sampled.txt"
