module: "RaceSketch"
data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/train.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 50000
save_sketch: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/race_sketch.pickle"
np_seed: 101
race:
  range: 4294967295 # (2*max_norm / bandwidth + 1)*power
  power: 4
  repetitions: 1
  num_classes: 2
  rehash: False
  max_coord: 10
  min_coord: -10
  lsh_function:
    name: "l2lsh"
    l2lsh:
      bandwidth: 0.15
      dimension: 18
      max_norm: 15
