module: "Loop"
device_id: 3
epochs: 3
train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/train.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 256
test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/test.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 256
validation_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/test.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 256
progress_train_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/small_train.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 256
progress_test_data:
  file: "/home/apd10/experiments/projects/summary_based_learning/DATA/SUSY/test.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
  sampler: "simple"
  simple:
    batch_size: 256
model:
  name: "MLP"
  MLP:
    input_dim: 18
    num_layers: 3
    hidden_size: 100
    num_class: 2
optimizer:
  name: "adam"
  adam:
    lr: 0.001
    weight_decay: 0
loss:
  name: "NLL"
progress_evaluator:
  name: "simple_print"
  simple_print:
      eval_itr: 5000
      eval_epoch: 1
